receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14250
  prometheus:
    config:
      global:
        scrape_interval: 5s
        evaluation_interval: 15s
      scrape_configs:
         - job_name: vote-ui
           static_configs:
           - targets: [vote-ui:8080]
processors:
  batch:
    timeout: 10s
  attributes/host-location: # adds an attribute to specify the location name
    actions:
       - key: host.location
         action: insert
         value: aueast
  transform/span-name: # creates an attribute with the span's original name
    trace_statements:
       - context: span
         statements:
         - set(attributes["span.name.original"], name)
  span/rename: # uses the attributes to create a new name of the span
    name:
      from_attributes: [span.name.original, host.location]
      separator: ':'
  filter/vote_count:
    metrics:
      include:
        match_type: strict
        metric_names:
          - vote_count
  tail_sampling:
    decision_wait: 10s # wait since the first span for making a decision
    num_traces: 100 # number of traces stored in memory
    expected_new_traces_per_sec: 10 # expected number of new traces
    policies:
      [
        {
          name: policy-1,
          type: status_code,
          status_code: {status_codes: [ERROR]}
        }
      ]
exporters:
  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
    tls:
      insecure: true
    external_labels:
      via: collector
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
  logging:
    verbosity: detailed
    sampling_initial: 1
    sampling_thereafter: 1
extensions:
  health_check:
service:
  extensions: [health_check] # Check health of collector at http://localhost:13133/
  pipelines:
    traces:
      receivers: [otlp, jaeger]
      # Only one processor can be used in a pipeline. Uncomment this processor to enable tail processor.
      #processors: [tail_sampling]
      processors: [batch, attributes/host-location, transform/span-name, span/rename]
      exporters: [jaeger, logging]
    metrics:
      receivers: [prometheus]
      processors: [batch, filter/vote_count]
      exporters: [prometheusremotewrite]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]