FROM mcr.microsoft.com/dotnet/aspnet:7.0-alpine AS base
WORKDIR /app
EXPOSE 8080

ENV ASPNETCORE_URLS=http://+:8080
ENV OTEL_DOTNET_AUTO_HOME=/app/otel-ai

FROM mcr.microsoft.com/dotnet/sdk:7.0-alpine AS build
ENV OTEL_DOTNET_AUTO_HOME=/app/otel-ai
WORKDIR /src
COPY ["vote-ui/vote-ui.csproj", "vote-ui/"]
COPY ["common/common.csproj", "common/"]
COPY ["Directory.Build.props", "./"]
RUN dotnet restore "vote-ui/vote-ui.csproj"
COPY . .
WORKDIR "/src/vote-ui"
RUN dotnet build "vote-ui.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "vote-ui.csproj" -c Release -o /app/publish /p:UseAppHost=false
# Download OTEL AI binaries
RUN curl -sSfL https://raw.githubusercontent.com/open-telemetry/opentelemetry-dotnet-instrumentation/v0.4.0-beta.1/otel-dotnet-auto-install.sh -O
RUN chmod +x ./otel-dotnet-auto-install.sh
RUN ./otel-dotnet-auto-install.sh

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
# Instrument OTEL
COPY --from=publish $OTEL_DOTNET_AUTO_HOME $OTEL_DOTNET_AUTO_HOME
ENV OTEL_SERVICE_NAME=vote-ui-ai
ENV OTEL_RESOURCE_ATTRIBUTES=deployment.environment=production,service.version=1.0.0.0
RUN . $OTEL_DOTNET_AUTO_HOME/instrument.sh
RUN ls -R
ENTRYPOINT ["dotnet", "vote-ui.dll"]